apiVersion: v2
appVersion: v0.5.9
dependencies:
  - name: common
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
description: A Helm chart for Kubernetes
name: tubearchivist
type: application
version: 0.9.1
