
global:
  # -- Set an override for the prefix of the fullname
  nameOverride:
  # -- Set the entire name definition
  fullnameOverride:
  # -- Set additional global labels. Helm templates can be used.
  labels: {}
  # -- Set additional global annotations. Helm templates can be used.
  annotations: {}


# -- Overrides for the rejson chart
redis:
  image:
    repository: "redis/redis-stack-server"
    tag: "6.2.6-v3"
  auth:
    enabled: false
  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
    # Enable Redis Json module
    loadmodule /opt/redis-stack/lib/rejson.so
  master:
    persistence:
      storageClass: ""
      size: 1Gi
  replica:
    replicaCount: 0

# -- Overrides for Elasticsearch chart
elasticsearch:
  image:
    repository: bitnami/elasticsearch
    tag: 8.6.0
  global:
    storageClass: ""
  extraEnvVars:
    - name: "discovery.type"
      value: "single-node"
    - name: xpack.security.enabled
      value: "true"
    - name: ELASTIC_PASSWORD
      value: "changeme"
  extraConfig:
    path:
      repo: /usr/share/elasticsearch/data/snapshot
  extraVolumeMounts:
    - name: snapshot
      mountPath: /usr/share/elasticsearch/data/snapshot
  extraVolumes:
    - name: snapshot
      emptyDir: {}

  master:
    masterOnly: false
    replicaCount: 1
    persistence:
      storageClass: ""
      size: 1Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 1000m
      limits:
        memory: 1Gi
        cpu: 1000m
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

controllers:
  main:
    strategy: Recreate
    containers:
      main:
        enabled: true
        image:
          repository: bbilly1/tubearchivist
          pullPolicy: IfNotPresent
          tag: v0.5.8 # keep in sync!
        env:
          # -- TZ: your time zone. If you don't know yours, you can look it up [[here]](https://www.timezoneconverter.com/cgi-bin/findzone/findzone).
          # your UID, if you want TubeArchivist to create files with your UID. Remove if you are OK with files being owned by the the container user.
          HOST_UID: 1000
          # above but GID.
          HOST_GID: 1000
          # change it to the address of the machine you're running this on. 
          # This can be an IP address or a domain name.
          TA_HOST: "localhost"
          TA_USERNAME: "admin"
          ES_URL: "http://tubearchivist-elasticsearch:9200"
          REDIS_CON: "redis://tubearchivist-redis:6379"
        envFrom:
          # -- ELASTIC_PASSWORD: pick a password for the elastic service. You won't need to type this yourself.
          - secretRef:
              name: elasticsearch # for ELASTIC_PASSWORD
          # -- TA_PASSWORD: pick a password to use when logging in.
          - secretRef:
              name: tubearchivist
  elasticsearch:
    strategy: Recreate
    containers:
      main:
        enabled: true
        image:
          repository: bbilly1/tubearchivist-es
          pullPolicy: IfNotPresent
          tag: 8.18.2
        envFrom:
          - secretRef:
              name: elasticsearch
        env:
          ES_JAVA_OPTS: -Xms1g -Xmx1g
          xpack.security.enabled: true
          discovery.type: single-node
          path.repo: /usr/share/elasticsearch/data/snapshot
        #expose:
        #  - "9200"
  redis:
    strategy: Recreate
    containers:
      main:
        enabled: true
        image:
          repository: redis
          pullPolicy: IfNotPresent
          tag: 8.4.0


# -- Configure persistence for the chart here.
# Additional items can be added by adding a dictionary key similar to the 'config' key.
# [[ref]](https://bjw-s.github.io/helm-charts/docs/common-library/common-library-storage)
# @default -- See below
persistence:
  youtube:
    enabled: true
    # -- The storage class to use for the PVC
    # @default -- See below
    storageClass: ""
    # -- The size of the PVC
    # @default -- See below
    size: 1Gi
    # -- The access mode of the PVC
    # @default -- See below
    accessMode: ReadWriteOnce
    # -- The path to mount the volume at
    # @default -- See below
    mountPath: /youtube

  cache:
    enabled: true
    # -- The storage class to use for the PVC
    # @default -- See below
    storageClass: ""
    # -- The size of the PVC
    # @default -- See below
    size: 1Gi
    # -- The access mode of the PVC
    # @default -- See below
    accessMode: ReadWriteOnce
    # -- The path to mount the volume at
    # @default -- See below
    mountPath: /cache

  es-data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ""
    size: 1Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      elasticsearch:
        main:
          - path: /usr/share/elasticsearch/data 

route: {}
# -- Configure the services for the chart here.
# Additional services can be added by adding a dictionary key similar to the 'main' service.
# @default -- See below
service:
  main:
    # -- Enables or disables the service
    enabled: true
    controller: main

    # -- Make this the primary service (used in probes, notes, etc...).
    # If there is more than 1 service, make sure that only 1 service is marked as primary.
    primary: true

    # -- Override the name suffix that is used for this service
    nameOverride:

    # -- Set the service type
    type: ClusterIP

    # -- Specify the externalTrafficPolicy for the service. Options: Cluster, Local
    # -- [[ref](https://kubernetes.io/docs/tutorials/services/source-ip/)]
    externalTrafficPolicy:

    # -- Specify the ip policy. Options: SingleStack, PreferDualStack, RequireDualStack
    ipFamilyPolicy:
    # -- The ip families that should be used. Options: IPv4, IPv6
    ipFamilies: []

    # -- Provide additional annotations which may be required.
    annotations: {}

    # -- Provide additional labels which may be required.
    labels: {}

    # -- Configure the Service port information here.
    # Additional ports can be added by adding a dictionary key similar to the 'http' service.
    # @default -- See below
    ports:
      http:
        # -- Enables or disables the port
        enabled: true

        # -- Make this the primary port (used in probes, notes, etc...)
        # If there is more than 1 service, make sure that only 1 port is marked as primary.
        primary: true

        # -- The port number
        port: 8000

        # -- Port protocol.
        # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
        # HTTPS and HTTPS spawn a TCP service and get used for internal URL and name generation
        protocol: HTTP

        # -- Specify a service targetPort if you wish to differ the service port from the application port.
        # If `targetPort` is specified, this port number is used in the container definition instead of
        # the `port` value. Therefore named ports are not supported for this field.
        targetPort: 8000

        # -- Specify the nodePort value for the LoadBalancer and NodePort service types.
        # [[ref]](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport)
        nodePort:

        # -- Allow adding additional match labels
        extraSelectorLabels: {}
  redis:
    enable: true
    controller: redis
    ports:
      redis:
        port: 6379
        targetPort: 6379
  elasticsearch:
    enable: true
    controller: elasticsearch
    ports:
      es:
        port: 9200
        targetPort: 9200

# -- Configure the ingresses for the chart here.
# Additional ingresses can be added by adding a dictionary key similar to the 'main' ingress.
# @default -- See below
ingress: 
  main:
    # -- Enables or disables the ingress
    enabled: true

    # -- Make this the primary ingress (used in probes, notes, etc...).
    # If there is more than 1 ingress, make sure that only 1 ingress is marked as primary.
    primary: true

    # -- Override the name suffix that is used for this ingress.
    nameOverride:

    # -- Provide additional annotations which may be required.
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    # -- Provide additional labels which may be required.
    labels: {}

    # -- Set the ingressClass that is used for this ingress.
    ingressClassName: # "nginx"

    ## Configure the hosts for the ingress
    hosts:
      - # -- Host address. Helm template can be passed.
        host: tube-archivist.local
        ## Configure the paths for the host
        paths:
          - # -- Path.  Helm template can be passed.
            path: /
            pathType: Prefix
            service:
              # -- Overrides the service name reference for this path
              name: tubearchivist-main
              # -- Overrides the service port reference for this path
              port: 8000

    # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
